[package]
name = "filesharing-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.0-beta.10" }
serde = "1"
mongodb = "2.1.0"
dotenv="0.15.0"
tokio-stream = "0.1.8"
